services:
  apache:
    image: php:8.3-apache
    container_name: xampp_apache
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./xampp/htdocs:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-available
    command: >
      bash -c "a2enmod rewrite proxy proxy_http &&
              a2ensite *.conf &&
              apache2-foreground && 
              a2ensite webapp.local && 
              a2ensite lading-page.local
              a2ensite dynamic-web.local"
    depends_on:
      - mariadb
      
  nodejs_webapp:
    build: ./nodejs
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./nodejs:/usr/src/app
    ports:
      - "3000:3000"
    command: "node sample-app-server.js"

  mariadb:
    image: mariadb:latest
    container_name: xampp_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: xampp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mariadb:/var/lib/mysql

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: xampp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb
