version: '3.8'

services:
  apache:
    image: httpd:2.4
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./static-sites:/var/www/html
      - ./config/vhosts:/usr/local/apache2/conf/extra/vhosts
    depends_on:
      - nodejs
    networks:
      - webnet

  nodejs:
    build: ./nodejs
    container_name: node_app
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=blog_app
    depends_on:
      - mariadb
    networks:
      - webnet

  mariadb:
    image: mariadb:10.5
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=blog_app
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

volumes:
  mariadb_data:
