services:
  apache:
    image: php:8.3-apache
    restart: always
    container_name: web_server
    ports:
      - "80:80"
    volumes:
      - ./xampp/htdocs:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/vhosts:/etc/apache2/sites-available
    
    # Enable modules rewrite, proxy, proxy_http and enable vhosts
    command: >
      bash -c "a2enmod rewrite proxy proxy_http &&
              a2ensite *.conf &&
              apache2-foreground && 
              a2ensite site-a.local && 
              a2ensite site-b.local &&
              a2ensite blog-app.local"
    depends_on:
      - nodejs
    networks:
      - webnet

  nodejs:
    build: ./nodejs
    tty: true # Keep the container running
    container_name: application_server
    environment:
      - DB_HOST=mariadb
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=blog_app
    ports:
      - "3000:3000"
    command: ["node", "blog-app/server.js"]
    depends_on:
      - mariadb
    networks:
      - webnet

  mariadb:
    image: mariadb:latest
    container_name: database_server
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blog_app
    volumes:
      - ./docker/mariadb:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    networks:
      - webnet

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    networks:
      - webnet

networks:
  webnet:
    driver: bridge

